[linux_input] add hotplug event detection with udev_monitor

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -747,6 +747,8 @@ SOFTWARE_RENDERING_FALSE
 SOFTWARE_RENDERING_TRUE
 TSLIB_LIBS
 TSLIB_CFLAGS
+LIBUDEV_LIBS
+LIBUDEV_CFLAGS
 SH772X_SHJPEG_DEP_LIBS
 SH772X_SHJPEG_DEP_CFLAGS
 SH772X_DEP_LIBS
@@ -1144,6 +1146,8 @@ SH772X_DEP_CFLAGS
 SH772X_DEP_LIBS
 SH772X_SHJPEG_DEP_CFLAGS
 SH772X_SHJPEG_DEP_LIBS
+LIBUDEV_CFLAGS
+LIBUDEV_LIBS
 TSLIB_CFLAGS
 TSLIB_LIBS'
 
@@ -1919,6 +1923,10 @@ Some influential environment variables:
               C compiler flags for SH772X_SHJPEG_DEP, overriding pkg-config
   SH772X_SHJPEG_DEP_LIBS
               linker flags for SH772X_SHJPEG_DEP, overriding pkg-config
+  LIBUDEV_CFLAGS
+              C compiler flags for LIBUDEV, overriding pkg-config
+  LIBUDEV_LIBS
+              linker flags for LIBUDEV, overriding pkg-config
   TSLIB_CFLAGS
               C compiler flags for TSLIB, overriding pkg-config
   TSLIB_LIBS  linker flags for TSLIB, overriding pkg-config
@@ -20047,6 +20055,81 @@ else
 $as_echo "no" >&6; }
 fi
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for LIBUDEV" >&5
+$as_echo_n "checking for LIBUDEV... " >&6; }
+
+if test -n "$LIBUDEV_CFLAGS"; then
+    pkg_cv_LIBUDEV_CFLAGS="$LIBUDEV_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libudev\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libudev") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBUDEV_CFLAGS=`$PKG_CONFIG --cflags "libudev" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$LIBUDEV_LIBS"; then
+    pkg_cv_LIBUDEV_LIBS="$LIBUDEV_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libudev\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libudev") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_LIBUDEV_LIBS=`$PKG_CONFIG --libs "libudev" 2>/dev/null`
+		      test "x$?" != "x0" && pkg_failed=yes
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+   	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBUDEV_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "libudev" 2>&1`
+        else
+	        LIBUDEV_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "libudev" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBUDEV_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: linuxinput will be build without libudev." >&5
+$as_echo "$as_me: WARNING: linuxinput will be build without libudev." >&2;}
+elif test $pkg_failed = untried; then
+     	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: linuxinput will be build without libudev." >&5
+$as_echo "$as_me: WARNING: linuxinput will be build without libudev." >&2;}
+else
+	LIBUDEV_CFLAGS=$pkg_cv_LIBUDEV_CFLAGS
+	LIBUDEV_LIBS=$pkg_cv_LIBUDEV_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+$as_echo "#define HAVE_LIBUDEV 1" >>confdefs.h
+
+fi
   fi
 fi
 
@@ -24415,7 +24498,7 @@ Building Input Drivers:
   Input Hub                 $enable_input_hub
   Joystick                  $enable_joystick
   Keyboard                  $enable_keyboard
-  Linux Input               $enable_linux_input
+  Linux Input               $enable_linux_input           $LIBUDEV_CFLAGS $LIBUDEV_LIBS
   LiRC                      $enable_lirc
   MuTouch touchscreen       $enable_mutouch
   Zytronic touchscreen      $enable_zytronic
@@ -24466,7 +24549,7 @@ Building Input Drivers:
   Input Hub                 $enable_input_hub
   Joystick                  $enable_joystick
   Keyboard                  $enable_keyboard
-  Linux Input               $enable_linux_input
+  Linux Input               $enable_linux_input           $LIBUDEV_CFLAGS $LIBUDEV_LIBS
   LiRC                      $enable_lirc
   MuTouch touchscreen       $enable_mutouch
   Zytronic touchscreen      $enable_zytronic
